### PR TITLE
changes instance definition visibility states

### LINKED ISSUE #70: Improve visibility settings for imported blocks
[https://discourse.mcneel.com/t/using-rhino3dm-in-blender/73510/242?u=fertig](url)

as mentioned in the post, block import leaves users with a bit of a confusing scene setup. there are some ways to solve this:

a) the instance definition collection and the geometry used in the collections could be set invisible,
this will be a bit tedious though with blocks including a lot of geometry

b) set up a new view layer that excludes all collections but the instance definitions, hide the instance definitions so they can be individually enabled to edit them. i would probably remove the geometry objects from their layer collection though, otherwise they're still going to stick around in the main view layer. or maybe recreate the layer hierarchy within the instance definitions (i have the feeling this could get out of hand real quick... :/ ). 

c) any other ideas?

setup example for b) using the sample file from the forum post.
image

### PR DESCRIPTION
**Pull request by lfertig**
# Creates a separate ViewLayer for instance definitions 

The added code resolves the problem of overlapping instance definition objects in the main scene view, that could until now only be resolved by manually changing visibility states of all instance definition objects and collections.

* When selecting the block import option, a separate view layer is created for instance definitions 
* exclusion states collections are set on default view layer and instance definition view layer
* instance definition view layer shows only the original definition collections and geometry for all instances
* the default view layer shows only the collection instances
* there are several options to further improve handling in the future (e.g. better visual layout of instance definitions)

## fixes / resolves
Resolves #70.

### CODE REVIEW

**Comment by lfertig** [comment]
two images to illustrate the setup:
idef_view
scene_view

**Comment by tsvilans** [comment]
Looks good!

Helpful to have a separate View Layer just for blocks.

**Comment by tsvilans** [comment]
Can you remove the `.3dm` and `.3dmbak` files from the PR? Keeps the repository clean :)

**Comment by lfertig** [comment]
ahh of course, I'll put them on ignore

**Comment by lfertig** [comment]
@tsvilans @jesterKing :
can i get an opinion from you guys? I'm still extending this and managed to cleanly lay out the block definitions to make editing them easier. this works well unless the blocks were defined with reference to the world origin and sit somewhere in 3d space (see example). I could wrestle them into the grid pattern, but i wonder if it's a good idea. it would work on reimport since the offsets are defined once when the collection definition is laid out the first time. It would break data consistency with the original file though... (which I'm doing anyways with the other blocks since I'm redefining the instance offset?)

image

other than that i think i can take the "experimental" tag of the import option, it handles relatively complex scenes with multiple levels of nested blocks without a problem..

image

**Comment by tsvilans** [comment]
@lfertig Looks awesome! So cool to have blocks as collections.

I'm wondering why you are laying out all the blocks in a grid pattern in the first place? Wouldn't you just center them around the block base point? I.e. block base point == world origin? Editing individual blocks then should just be a matter of isolating the corresponding collection, and, upon import, all the block collections could simply be turned off (unchecked)...

**Comment by lfertig** [comment]
i put them all to world origin in the beginning. yesterday i made an effort, took the sample project here and tried to recreate the scene as i rendered it in rhino. fact is, you end up toggling visibility in the outliner/hiding/unhiding/selecting by material/by collection all the time and its pretty tedious. if you have a small block, it might be hidden by overlapping larger geometry. laying them out like this seemed the most sensible option, since you can easily define the instance_offset in the collection. 

i guess i would at least offer it as an option since it greatly facilitates working with the file

**Comment by tsvilans** [comment]
Yes, sounds like a good option to have. Isolating collection instances should be a Blender feature. There are so many times where that would be useful. Similar how you can press `/` to isolate a group of objects, you should be able to select a collection instance and isolate the objects in that collection.

**Comment by lfertig** [comment]
ahh that'd be great. i don't see a timeline though? is this a proper bugreport?

anyway, this here seems robust enough after working with it for another day to merge it, unless there's any reason not to?

**Comment by tsvilans** [comment]
Looks good to me!

**Pull request merged**
