### PR TITLE
groups all layer collections into one main "Layers" collection

### LINKED ISSUE #42: Clean up Layer import: Bundle layer collections, optionally skip empty layers
Importing files with lots of layers results in a lot of collections being created under the main scene collection, which complicates navigating the file in the outliner. Layers should be bundled under one main "Layers" collection. 

In order to prevent empty collections, add an option to skip empty layers on import.

[https://discourse.mcneel.com/t/using-rhino3dm-in-blender/73510/162?u=fertig](url)

### PR DESCRIPTION
**Pull request by lfertig**
# partial fix to #42 

groups all layer collections into one main "Layers" collection to make file easier to navigate in outliner

## detailed explanation
*adds new collection "Layers"
*links "Layers" to toplayer collection
*links all parent layers to new "Layers" collection (children are still linked to their parents)

## fixes / resolves
partially Fixes #42

### CODE REVIEW

**Comment by jesterKing** [comment]
LGTM

**Comment by lfertig** [comment]
I don't find the time right now to address skipping the empty layers. If nothing else speaks against it I'd merge this as is? IMO it would really help the workflow having this implemented.

**Comment by tsvilans** [comment]
Let's hold off on merging until we have a bit of time to look into it. I'll try to take a look this weekend. It would be good to address some of the issues before merging. Saves dealing with complaints later :P

**Comment by tsvilans** [comment]
Sorry, confused this PR with another one. Looks good.

**Pull request merged**
